# -- Main Menu --
# The main menu is displayed in the header at the top of the page.
# Acceptable parameters are name, pageRef, page, url, title, weight.
# 
# The simplest menu configuration is to provide:
#   name = The name to be displayed for this menu link
#   pageRef = The identifier of the page or section to link to
#
# By default the menu is ordered alphabetically. This can be
# overridden by providing a weight value. The menu will then be
# ordered by weight from lowest to highest.

[[main]]
  name = ":pencil2:Posts"
  pageRef = "posts"
  weight = 10

# [[main]]
#   name = "Categories"
#   pageRef = "categories"
#   weight = 20

[[main]]
  name = ":round_pushpin:Tags"
  pageRef = "tags"
  weight = 20
  
#[[main]]
#  name = ":pick:Projects"
#  url = "http://114.215.149.199/"
#  weight = 30

[[main]]
  name = ":dizzy:ACM Hub"
  pageRef = "acm"
  weight = 30 

[[main]]
  name = ":newspaper_roll:Publications"
  pageRef = "publications"
  weight = 40  

# -- Footer Menu --
# The footer menu is displayed at the bottom of the page, just before
# the copyright notice. Configure as per the main menu above.

[[footer]]
  name = "Microsoft Research Asia"
  url = "https://www.msra.cn/"
  weight = 6

#[[footer]]
 # name = "ByteDance"
 # url = "https://www.bytedance.com/zh/"
 # weight = 7
  
[[footer]]
  name = "IRLab@SDU"
  url = "https://ir.sdu.edu.cn/"
  weight = 10
  
[[footer]]
  name = "Shandong University"
  url = "https://www.sdu.edu.cn/"
  weight = 20

[[footer]]
  name = "Nesto"
  url = "http://nesto.cupof.beer/"
  weight = 30
  
[[footer]]
  name = ":hugs:"
#   url = "http://nesto.cupof.beer/"
  pageRef = "/"
  weight = 5
